# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphPainter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='graphPainter.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12graphPainter.proto\"A\n\x0c\x43hartRequest\x12\r\n\x05\x64\x61tas\x18\x01 \x01(\t\x12\x11\n\ttokenInfo\x18\x02 \x01(\t\x12\x0f\n\x07options\x18\x03 \x01(\t\"\x1e\n\rChartResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\"\"\n\x0fSayHelloMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa8\x01\n\x13GraphPainterService\x12-\n\x05Greet\x12\x10.SayHelloMessage\x1a\x10.SayHelloMessage\"\x00\x12\x33\n\x10PaintCandlestick\x12\r.ChartRequest\x1a\x0e.ChartResponse\"\x00\x12-\n\nPaintChart\x12\r.ChartRequest\x1a\x0e.ChartResponse\"\x00\x62\x06proto3'
)




_CHARTREQUEST = _descriptor.Descriptor(
  name='ChartRequest',
  full_name='ChartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='datas', full_name='ChartRequest.datas', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tokenInfo', full_name='ChartRequest.tokenInfo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='options', full_name='ChartRequest.options', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=87,
)


_CHARTRESPONSE = _descriptor.Descriptor(
  name='ChartResponse',
  full_name='ChartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ChartResponse.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=119,
)


_SAYHELLOMESSAGE = _descriptor.Descriptor(
  name='SayHelloMessage',
  full_name='SayHelloMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='SayHelloMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['ChartRequest'] = _CHARTREQUEST
DESCRIPTOR.message_types_by_name['ChartResponse'] = _CHARTRESPONSE
DESCRIPTOR.message_types_by_name['SayHelloMessage'] = _SAYHELLOMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChartRequest = _reflection.GeneratedProtocolMessageType('ChartRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHARTREQUEST,
  '__module__' : 'graphPainter_pb2'
  # @@protoc_insertion_point(class_scope:ChartRequest)
  })
_sym_db.RegisterMessage(ChartRequest)

ChartResponse = _reflection.GeneratedProtocolMessageType('ChartResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHARTRESPONSE,
  '__module__' : 'graphPainter_pb2'
  # @@protoc_insertion_point(class_scope:ChartResponse)
  })
_sym_db.RegisterMessage(ChartResponse)

SayHelloMessage = _reflection.GeneratedProtocolMessageType('SayHelloMessage', (_message.Message,), {
  'DESCRIPTOR' : _SAYHELLOMESSAGE,
  '__module__' : 'graphPainter_pb2'
  # @@protoc_insertion_point(class_scope:SayHelloMessage)
  })
_sym_db.RegisterMessage(SayHelloMessage)



_GRAPHPAINTERSERVICE = _descriptor.ServiceDescriptor(
  name='GraphPainterService',
  full_name='GraphPainterService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=158,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='Greet',
    full_name='GraphPainterService.Greet',
    index=0,
    containing_service=None,
    input_type=_SAYHELLOMESSAGE,
    output_type=_SAYHELLOMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PaintCandlestick',
    full_name='GraphPainterService.PaintCandlestick',
    index=1,
    containing_service=None,
    input_type=_CHARTREQUEST,
    output_type=_CHARTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PaintChart',
    full_name='GraphPainterService.PaintChart',
    index=2,
    containing_service=None,
    input_type=_CHARTREQUEST,
    output_type=_CHARTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRAPHPAINTERSERVICE)

DESCRIPTOR.services_by_name['GraphPainterService'] = _GRAPHPAINTERSERVICE

# @@protoc_insertion_point(module_scope)
